### ISSUE TITLE
.Send delay not delaying

### ISSUE THREAD

**Issue by jsavko** [mpneuried/rsmq-worker#1]
I've been experimenting with your message queue a bit. 

I've been really impressed with it overall, but I can't get the worker.send delay to actually delay the message. 

For my test I was attempting to send the received message after a 60 second delay. 

```
 worker.on( "message", function( msg, next ){
    worker.send(msg, 60);`
    next()`
  });`
```

However the message is processed immediately.    Am I missing something?

**Comment by mpneuried** [comment]
I will have a look at it and check it next week.

**Comment by mpneuried** [comment]
After a short look into the code I can provide a quick workaround.
Just add an empty function to `.send( msg, 60, function(){} )`.

I will fix the argument dispatch next week, to make the callback in combination with the delay optional.

**Comment by jsavko** [comment]
Yep that does indeed fix the delay.   

Thank you.
