### ISSUE TITLE
QUESTION: what does a timeout event signify?

### ISSUE THREAD

**Issue by mrose17** [mpneuried/rsmq-worker#10]
first, a great package!

here's my question: i have a 'data' event listener (but not a 'message' event listener). the last thing the 'data' listener does is to call worker.del(resp.id).  

however, 3 seconds (the default), the 'timeout' event fires. what am i missing? thanks!

**Comment by mpneuried** [comment]
you should use the [`message` event](https://github.com/mpneuried/rsmq-worker#message), because this one delivers the `next()` function to control the timeouts

```js
worker.on( "message", function( message, next, msgid ){
    // process message ... 
    next();
});
```

**Comment by mrose17** [comment]
@mpneuried - thanks! the reason i'm using 'data' instead of 'message' is that 'message' doesn't return the 'id' of the message, just the payload... any suggestions? thanks!

**Comment by mpneuried** [comment]
As you can see above, you'll get the `msgid` as third argument, of the `message` event.
Did you missed that point, or do you have a problem with that?

**Comment by mrose17** [comment]
my bad! totally missed that, sorry!
