### ISSUE TITLE
Message Queue not deleting message

### ISSUE THREAD

**Issue by RicardoVaranda** [mpneuried/rsmq-worker#12]
I'm using this example:
http://smrchy.github.io/rsmq/rsmq-worker/#-initialize

I have the RSMQ running on an node server. I have an end point which once accessed creates a message and should delete it once it receives it since next() is called and delete is true by default. The issue is the next time I access that end point the message is actually not deleted and creates an extra message on top of that.

For Example:

Web server listening at: http://0.0.0.0:3001
Browse your REST API at http://0.0.0.0:3001/explorer

FIRST REQUEST:

Message sent. ID: eec8occ2q9rXcY6MY8ZDlQoZGeLcmB1Q 1
Worker  Hello World eec8occ2q9rXcY6MY8ZDlQoZGeLcmB1Q
DELETED eec8occ2q9rXcY6MY8ZDlQoZGeLcmB1Q undefined

SECOND REQUEST:

Message sent. ID: eec8oeoo8100wB8Zm1GzEevLGqAMtTL7 2
Worker  Hello World eec8oeoo8100wB8Zm1GzEevLGqAMtTL7
Worker  Hello World eec8oeoo8100wB8Zm1GzEevLGqAMtTL7
DELETED eec8oeoo8100wB8Zm1GzEevLGqAMtTL7 undefined
DELETED eec8oeoo8100wB8Zm1GzEevLGqAMtTL7 undefined

THIRD REQUEST:

Message sent. ID: eec8ohx4d3PmldXOQ5luobKXAMolh3OJ 3
Worker  Hello World eec8ohx4d3PmldXOQ5luobKXAMolh3OJ
Worker  Hello World eec8ohx4d3PmldXOQ5luobKXAMolh3OJ
Worker  Hello World eec8ohx4d3PmldXOQ5luobKXAMolh3OJ
DELETED eec8ohx4d3PmldXOQ5luobKXAMolh3OJ undefined
DELETED eec8ohx4d3PmldXOQ5luobKXAMolh3OJ undefined
DELETED eec8ohx4d3PmldXOQ5luobKXAMolh3OJ undefined

**Comment by mpneuried** [comment]
Hi,
i did a test too.

**Code:**
```
var RSMQWorker = require( "rsmq-worker" );
var worker = new RSMQWorker( "myqueue", {} );

worker.on( "message", function( msg, next, id ){
 console.log("MESSAGE", id, msg );
 next()
});

// optional error listeners
worker.on('error', function( err, msg ){
 console.log( "ERROR", err, msg.id );
});
worker.on('exceeded', function( msg ){
 console.log( "EXCEEDED", msg.id );
});
worker.on('timeout', function( msg ){
 console.log( "TIMEOUT", msg.id, msg.rc );
});

worker.start();
```

**Run:**
```sh
$ node test.js                                                                                                                                    ✘  10:52:46
MESSAGE eef6lu6d48QZE2EI0VT3fLCisCiSlMUp Hello world
MESSAGE eef6lzp4k0IAVBI79HoEEuOS2sYhN1Fc Hello Foo
MESSAGE eef6m2knjrhGA0ilbLxZLDdIE4mfAO9k Hello Bar
MESSAGE eef6m8qwwrBcGLmPd6n1kLFBaKV90p1M Hello Narf
```

```sh
$ rsmq -q myqueue send "Hello world" 
eef6lu6d48QZE2EI0VT3fLCisCiSlMUp
$ rsmq -q myqueue send "Hello Foo" 
eef6lzp4k0IAVBI79HoEEuOS2sYhN1Fc
$ rsmq -q myqueue send "Hello Bar" 
eef6m2knjrhGA0ilbLxZLDdIE4mfAO9k
$ rsmq -q myqueue send "Hello Narf" 
eef6m8qwwrBcGLmPd6n1kLFBaKV90p1M
```

**Comment by mpneuried** [comment]
So as you can see, i could noct reproduce your point ... 
Can you give me a more detailed example, so i can reproduce it !?

**Comment by RicardoVaranda** [comment]
Sorry for the slow reply, the behavior was as intended.
