### ISSUE TITLE
option.interval 

### ISSUE THREAD

**Issue by how2945ard** [mpneuried/rsmq-worker#19]
```
 var worker = new RSMQWorker( "myqueue", {
        interval: [ .1, 1 ],                // wait 100ms between every receive and step up to 1,3 on empty receives
        invisibletime: 2,                       // hide received message for 5 sec
        maxReceiveCount: 2,                 // only receive a message 2 times until delete
        autostart: true,                        // start worker on init
        customExceedCheck: fnCheck  // set the custom exceed check
    });
```

you said in the README file 

> wait 100ms between every receive and step up to 1,3 on empty receives

what does the  `1,3` part mean? is that a typo? or 1.3? but why?

**Comment by mpneuried** [comment]
It's not a typo, but the configuration and description are not matching 100% ;-)

The option `interval` can:

**A.)**
be a Number so the worker will poll the queue every `n` seconds  (e.g. `interval: .5` = twice a second second)

**B.)**
be an Array of Numbers. On start `interval[0]` is the time to poll the queue.
Everytime the worker receives an empty response *(queue is empty)* the next `interval` will be used to wait for the next poll *(`interval[+1]`)* until the last definition `interval[ n ]` was reached. On every received message the wait time will be reset to `interval[0]`.

>E.g: `interval: [ .2, 1, 3 ]`
- 1st poll -> no message -> wait `.2s` = `200ms`
- 2nd poll -> no message -> wait `1s`
- 3rd poll -> no message -> wait `3s`
- 4th poll -> no message -> wait `3s`
- 5th poll -> 1 message -> wait `.2s`
- 6th poll -> no message -> wait `1s`
- 7th poll -> 1 message -> wait `.2s`
- 8th poll -> 1 message -> wait `.2s`
- 9th poll -> no message -> wait `.2s`
- 10th poll -> no message -> wait `1s`
...

**Comment by mpneuried** [comment]
Does this clear your question?

**Comment by how2945ard** [comment]
Yes, that a very clear answer.
Thanks!

**Comment by smoakey** [comment]
@how2945ard can you please put this in the Readme? this was very helpful to my understanding.

**Comment by mpneuried** [comment]
@smoakey see https://github.com/mpneuried/rsmq-worker/blob/master/README.md#options-interval

**Comment by smoakey** [comment]
@mpneuried thanks for doing that!! Also sorry I just realized I "at'd" the issue submitter not you :)
