### ISSUE TITLE
ReplyError: ERR unknown command 'time'

### ISSUE THREAD

**Issue by irvingswiftj** [mpneuried/rsmq-worker#23]
I'm getting the following error causing me a fatal error to my app!

ReplyError: ERR unknown command 'time'
at parseError (/myproject/socket-server/node_modules/redis-parser/lib/parser.js:163:12)
at parseType (/myproject/socket-server/node_modules/redis-parser/lib/parser.js:224:14)

**Comment by mpneuried** [comment]
I checked my code, but i'm not using `TIME` directly.
So it's probably more a case inside rsmq.
But with only these two lines of code i, or  the rsmq developer @smrchy (smrchy/rsmq#36), cannot help you.
So please help us and send us mor information.
An example code to reproduce this issue would help us most.

**Comment by irvingswiftj** [comment]
I have stopped using this module for now and create a queuing system in pure js (time was a real constraint!).

I'm using centos and I wonder if there is a minimum version number of redis that I should be running:

`[root@XXXXXXXXXXXX ~]# yum info redis
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.vorboss.net
 * epel: mirrors.ircam.fr
 * extras: mirror.vorboss.net
 * updates: centos.hyve.com
Installed Packages
Name        : redis
Arch        : x86_64
Version     : 2.4.10
Release     : 1.el6
Size        : 668 k
Repo        : installed
From repo   : epel
Summary     : A persistent key-value database
URL         : http://redis.io
License     : BSD
Description : Redis is an advanced key-value store. It is similar to memcached but the data
            : set is not volatile, and values can be strings, exactly like in memcached, but
            : also lists, sets, and ordered sets. All this data types can be manipulated with
            : atomic operations to push/pop elements, add/remove elements, perform server side
            : union, intersection, difference between sets, and so forth. Redis supports
            : different kind of sorting abilities.
`

**Comment by smrchy** [comment]
Well, rsmq uses the `TIME` command. 

http://redis.io/commands/time

As you can see this is available sind 2.6.0. You seem to be running 2.4.10 which is really old (from 2012). You should consider upgrading. Then maybe give rsmq another try.

**Comment by irvingswiftj** [comment]
Ok, that is fine, I'll have to resolve this. On the readme, could there please be a min requirement section that states the minimum redis version?

**Comment by smrchy** [comment]
The main RSMQ repo has this Note. Added it to rsmq-worker as well.
