### ISSUE TITLE
How to send a message from PHP redis?

### ISSUE THREAD

**Issue by janis91** [mpneuried/rsmq-worker#32]
Hi, I have the usecase that i want to listen for messages with a few nodejs apps, but push from a PHP application. Which commands do I have to use to push a message in the queue from my php app, that it will be recognized by the rsmq workers?

**Comment by mpneuried** [comment]
You could use rest-rsmq
https://github.com/smrchy/rest-rsmq
This is a small (probably) express server that exposes the rsmq methods to a rest interface

**Comment by mpneuried** [comment]
Does this module fit your needs?

**Comment by janis91** [comment]
I will evaluate it. Thanks so far!
