### ISSUE TITLE
How could to disable multiple messages receivers

### ISSUE THREAD

**Issue by palmadias** [mpneuried/rsmq-worker#9]
I would like to read one message at time,without parallel. Is it possible?

Tks.

**Comment by mpneuried** [comment]
This works is internally in series.
So yes it's possible, because this is the only mode, except you are using multiple worker instances.

The parallel execution is currently just an [idea to implement](https://github.com/mpneuried/rsmq-worker#todosideas)

**Comment by Gouthamve** [comment]
Hi,

Are you sure only one thing is happening at a time?

I am having the processFunc `on("message", processFunc)` and I am seeing multiple messages being processed at once.

**Comment by mpneuried** [comment]
i looked at the code again and in theory the next message should be pulled after you called `next()`.
If you are calling `next()` direct after you received a message or you defined a very low timeout, multiple tasks in parallel are possible.

If you having already problems, you can provide me an example so i can reproduce your case.

The typical usage is:
```js
worker.on( "message", function( message, next, msgid ){
    // process message ... 
    next();
});
```

**Comment by Gouthamve** [comment]
Aah! My job takes > 1 min to finish, hence I must have hit the timeout.

I will now set the proper timeout, thanks!

**Comment by mpneuried** [comment]
If not done yet, i recommend to listen to the error events ;-)

```js
 // optional error listeners
  worker.on('error', function( err, msg ){
      console.log( "ERROR", err, msg.id );
  });
  worker.on('exceeded', function( msg ){
      console.log( "EXCEEDED", msg.id );
  });
  worker.on('timeout', function( msg ){
      console.log( "TIMEOUT", msg.id, msg.rc );
  });
```
